---
title: "My Idea For The Mini Project"
author: "Benjamin J. Fox"
date: "2026-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Idea in Question:
What has been the economic impact of large music tours after the pandemic? This idea has largely been inspired by many articles relating to the noted GDP and local spending increase allegedly generated by Taylor Swift's Eras Tour. In July 2023, Joseph Pisani at the Wall Street Journal coined the term [Taylornomics](https://www.wsj.com/arts-culture/taylor-swift-taylornomics-concert-eras-tour-local-economy-9fa1d492) to discuss the trend of increased spending.Taylor Swift being the largest pop star in the world notwithstanding, the success of the Eras Tour on a local economic level raises some questions. The most important one, in my mind, being whether or not this is an isolated phenomenon. Do other massive music tours have a similar positive effect on the economies they visit? Possibly also comparing the Superbowl and the Solar Eclipse economic effect.

## The Scale of the Question
Concert tours, especially with the largest acts in the world, are inevitably massive in scale. The Eras Tour, the highest grossing tour of all time, even adjusting for inflation, played 149 shows. The second highest grossing, Coldplay's Music of the Spheres World tour, played 223. All tours large enough to make an economic impact are massive in most ways. Thus, the ways in which this specific project can measure large tours must be scaled down.

### The Tours
Beyond just the artists specifically, which tours to even cover also comes down to time. What time period should be noted as particularly notable. If you look at the highest grossing tours of all time, a large amount of them happened between 2020 and 2025. Closer to 2022 to 2025 but I'm going to expand to that initial six year gap for simplicity's sake. Tours that both started and ended in that time frame, and specifically the tours on the list of the highest grossing of all time. The specific list of tours that qualifies is below.

1. Taylor Swift's Eras Tour
2. The Weeknd's After Hours til Dawn tour
3. Coldplay's Music of the Spheres WOrld Tour
4. Ed Sheeran's Mathematics Tour (Officially called the +−=÷× Tour)
5. Bruce Springsteen and the E Street Band's 2023-2025 Tour
6. Metallica's M72 Tour
7. P!NK's Summer Carnival Tour
8. Beyoncé's Renaissance World Tour
9. Harry Styles' Love on Tour

### The Cities
In part because of the absurd amount of people that exist generally, and amount of large cities across the world, the focus of this project must scale down to accommodate. Therefore, I will only focus on a handful of large cities in the United States. Each city has its own set of large venues that will be accounted for on their respective tour when necessary. Until that bridge is crossed however, the list of cities/metro areas is listed below.

- Boston
- New York City
- Philadelphia
- Chicago
- Los Angeles

## Sourcing Data
This has been the trickiest part by far. Trying to find financial reports, specifically by week for certain industries has been difficult. Most reports on Taylor Swift's impact have focused on transit, restaurant, and hotel revenues. So I will too. Where I'm getting that information from is going to vary by city. Now I'm wondering if I should scale down even focusing on one industry. 

### Hotels
Less so revenue, moreso hotel occupancy

### Transit
Different cities have different public transport networks, but mostly focusing on subways and trains as our sort of visitors are more likely to be using them or ubers to get to and from the show. Tables being sourced are below

- [Boston](https://mbta-massdot.opendata.arcgis.com/datasets/MassDOT::mbta-commuter-rail-ridership-by-service-date-and-line/explore)
- [New York](https://data.ny.gov/Transportation/MTA-Daily-Ridership-Data-2020-2025/vxuj-8kew/about_data)
- Philadelphia: I've been finding by month
- [Chicago](https://data.cityofchicago.org/Transportation/CTA-Ridership-Daily-Boarding-Totals/6iiy-9s97/about_data)
- Los Angeles: I've been finding by month

Traffic tolls. Flight revenues. Cell phone movement.

## Modeling
Tblae

## Stakeholders
The primary stakeholders in this matter are local businesses themselve. This project is not planning on looking at the economics of tours themselves, such as the revenue from tickets and merchandise for the artist and for the venue. Instead, this project plans on analyzing the surrounding metro area. Can local businesses, especially those who would be catering to those only visiting the area for this show, expect a noticeable increase in revenue when a major artist comes to town? Should the owners of hotels and restaurants expect to see an increase in reservations? Should transit services, such as Uber, Lyft, and local public transportation, expect to see a surge in use? Most importantly in my mind, is it worthwhile for these cities to ensure that major artists want to come perform there for the sake of their bottom line?

## Ethical Ramifications
